import axios from "axios";

const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000/api";

// Mock courses data with expanded descriptions
const forexCoursesData = [
  { "_id": "1", "title": "Beginner's Guide to Trading: Types of Trading (Part 1)", "price": "20", "discount": "0", "category": "Forex", "image": "/svg/forextrading.svg", "details": "Master the fundamentals of trading by exploring different trading styles. This comprehensive course introduces you to the core concepts of day trading, swing trading, and long-term investing strategies.", "description": "Welcome to your comprehensive journey into the world of trading. Part 1 of our beginner's guide provides an in-depth exploration of the foundation of successful trading by systematically breaking down the various types of trading approaches available to modern traders. Throughout this course, you will learn how to identify which trading style aligns perfectly with your personal financial goals, risk tolerance, and personality traits. This course covers the essential characteristics of each trading type including timeframes, capital requirements, stress levels, and profit potential. You'll discover the differences between day traders, swing traders, position traders, and long-term investors, understanding how each approach works in various market conditions. We'll examine real-world examples and case studies of successful traders who specialize in different styles, showing you the practical applications of theory. By the end of this module, you'll have a solid understanding of different trading methodologies, helping you build confidence before diving into more advanced strategies. Perfect for anyone new to the financial markets who wants to establish a strong foundational knowledge and avoid common beginner mistakes.", "reviews": [] },
  { "_id": "2", "title": "Beginner's Guide to Trading: Types of Trading (Part 2)", "price": "30", "discount": "0", "category": "Forex", "image": "/svg/forextrading.svg", "details": "Continue your trading education with advanced trading types and hybrid strategies. Learn how to combine different approaches for maximum market advantage.", "description": "Build upon your foundational knowledge with Part 2 of our comprehensive beginner's guide to trading. This course delves considerably deeper into specialized trading types and hybrid strategies that blend multiple approaches for superior results. Throughout this module, you will discover how professional traders strategically combine different methodologies to maximize their success across various market conditions and volatility environments. Gain extensive insights into specialized techniques including scalping strategies for micro-movements, sophisticated position trading for capturing major trends, and algorithmic approaches that leverage technology. Learn the art of adapting your strategy based on real-time market dynamics, understanding when to switch between different approaches. We'll explore the concept of style fusion where traders combine elements from different trading philosophies to create a personalized approach. You'll understand how macroeconomic factors influence which trading style is most effective at any given time. This comprehensive module includes practical exercises, strategy comparisons, and detailed market analysis to prepare you for real-world trading scenarios that you'll encounter in live markets.", "reviews": [] },
  { "_id": "3", "title": "Beginner's Guide to Trading: Types of Trading (Part 3)", "price": "40", "discount": "0", "category": "Forex", "image": "/svg/forextrading.svg", "details": "Complete your foundational understanding with advanced concepts and practical applications. Learn to execute strategies effectively in live market conditions.", "description": "Conclude your comprehensive beginner's trading journey with Part 3, where profound theory meets practical real-world execution. This final and critical module of the Types of Trading series focuses extensively on practical application and real-world execution in live market environments. Throughout this course, you'll learn how to implement different trading types in actual market conditions while managing the emotional and psychological challenges that every trader faces. Understand the multifaceted psychological aspects of trading including fear, greed, overconfidence, and discipline. You'll develop your personal trading plan with clear objectives, risk parameters, and performance metrics. Master comprehensive risk management techniques that are specifically tailored to each trading style you've learned. Discover how successful traders adapt their approaches to changing market environments, volatility spikes, and unexpected geopolitical events. This module covers position sizing strategies, capital allocation methods, and portfolio construction techniques. You'll learn from real trading scenarios, common pitfalls, and recovery strategies from drawdowns. By completing this course, you'll have a complete toolkit for beginning your trading career with realistic expectations and professional-level preparation.", "reviews": [] },
  { "_id": "4", "title": "Getting Started: Introduction to Trading Platforms", "price": "50", "discount": "0", "category": "Forex", "image": "/svg/laptop.svg", "details": "Get hands-on experience with industry-standard trading platforms. Learn navigation, tools, and features essential for executing trades efficiently.", "description": "Explore the essential digital tools and platforms that power modern professional trading around the world. This comprehensive course introduces you thoroughly to the leading trading platforms used by professional traders and institutional investors worldwide. You'll develop a deep understanding of the interface layouts, comprehensive chart analysis tools, and sophisticated order execution methods available on major platforms. Learn how to customize your workspace intelligently for optimal productivity, taking advantage of multiple monitors, custom watchlists, and alert systems. Discover the vast array of advanced features that can dramatically enhance your trading efficiency including one-click trading, bracket orders, and conditional orders. This course covers everything from basic navigation to sophisticated analysis tools, ensuring you can confidently operate professional trading platforms like a seasoned trader. You'll understand the differences between various platforms and how to choose the right one for your specific needs. We'll explore keyboard shortcuts, automation capabilities, and integration with other trading tools. By the end, you'll navigate professional trading platforms with complete confidence and efficiency.", "reviews": [] },
  { "_id": "5", "title": "Trading Strategies: Introduction to Scalp Trading", "price": "60", "discount": "0", "category": "Forex", "image": "/svg/priceaction.svg", "details": "Master the art of quick profits with scalp trading. Learn to identify micro-movements and execute rapid trades with precision.", "description": "Discover one of the most dynamic and exciting trading strategies in the modern financial markets. This comprehensive course introduces you in detail to scalp trading, a sophisticated technique focused specifically on capturing small price movements over extremely short timeframes, typically seconds to minutes. Learn the specific technical indicators and timing mechanisms that successful scalpers worldwide use to identify micro-movements. Understand the critical importance of speed and precision in scalp trading, where milliseconds can mean the difference between profit and loss. Develop comprehensive strategies for managing rapid-fire trades while maintaining strict risk control and emotional discipline. This course covers entry and exit signals, position sizing for scalping, managing slippage, and leveraging tools like limit orders and direct market access. You'll understand the market microstructure and how to exploit inefficiencies in real-time. Learn about different scalping approaches including time-based scalping, indicator-based scalping, and price action scalping. Perfect for traders who thrive on fast-paced action, have rapid decision-making skills, and want to capitalize consistently on intraday volatility without holding positions overnight.", "reviews": [] },
  { "_id": "6", "title": "Trading Strategies: Introduction to Swing Trading", "price": "70", "discount": "0", "category": "Forex", "image": "/svg/swing.svg", "details": "Capitalize on medium-term price swings with swing trading. Learn to identify reversal points and ride profitable trends.", "description": "Transform your comprehensive understanding of intermediate-term trading with our detailed and practical swing trading course. This sophisticated strategy focuses specifically on capturing price swings that typically last anywhere from multiple days to several weeks, capturing substantial price movements. Throughout this course, you'll learn to meticulously identify key support and resistance levels using multiple technical analysis tools and methods. Recognize the specific chart patterns that reliably signal potential reversals and continuation patterns. Master the art of timing your entries and exits for maximum profitability while managing multiple swing trades simultaneously. Discover exactly how professional swing traders use advanced technical analysis, volume patterns, and trend analysis to stay consistently ahead of market movements. Learn about the importance of timeframe selection and how using multiple timeframes dramatically improves your decision-making accuracy. This course explores swing trading setups, risk-reward ratios, and position management throughout multi-day trades. You'll understand how to use swing trading indicators effectively and avoid false signals. This course perfectly balances the rapid pace of scalping with the patience required for long-term investing, making it ideal for traders seeking consistent profits with manageable risk.", "reviews": [] },
  { "_id": "7", "title": "Trading Strategies: Introduction to Intraday Trading", "price": "80", "discount": "0", "category": "Forex", "image": "/svg/intradaytrading.svg", "details": "Master day-to-day trading strategies that capitalize on daily price movements. Learn timing, entry points, and exit strategies.", "description": "Enter the exciting and dynamic world of intraday trading where substantial fortunes can be made within a single trading session from opening bell to closing bell. This comprehensive and practical course teaches you the detailed strategies, precise timing, and sophisticated psychology of day traders who operate entirely within a single market day. Throughout this course, you'll learn to identify morning gaps and opening volatility, crucial for capturing the day's most profitable moves. Master the skill of tracking intraday momentum using real-time indicators and price action analysis. Learn to execute precise entry and exit strategies that capitalize on the unique market dynamics that occur within a single trading session. Understand the unique risks and rewards inherent in intraday trading, including increased transaction costs and tax implications. Develop a disciplined psychological approach to this fast-moving market segment where emotions can severely impact decision-making. This course covers intraday chart patterns, support and resistance in shorter timeframes, and specific trading setups that work during different sessions. You'll learn about session-specific characteristics including the opening hour volatility, mid-day consolidation, and the afternoon reversal potential. By the end of this course, you'll have the strategies and discipline needed to profit consistently from intraday price movements.", "reviews": [] },
  { "_id": "8", "title": "Trading Strategies: Introduction to Long-Term Trading", "price": "90", "discount": "0", "category": "Forex", "image": "/svg/sharemarket.svg", "details": "Build wealth through patient, strategic long-term investing. Learn to hold positions through market cycles for substantial returns.", "description": "Discover and master the profound power of patience and strategic positioning in long-term trading and wealth building. This comprehensive course explores the detailed strategies for traders and investors who believe in holding positions through multiple complete market cycles to capture truly major price movements and trends. Throughout this course, you'll learn fundamental analysis techniques that go far beyond simple price charts, understanding company valuations, economic indicators, and market cycles. Learn how to identify mega-trends that can last months or years, positioning yourself to profit from these enormous moves. Understand the critical importance of patience in achieving truly significant returns that compound over time into life-changing wealth. Master comprehensive position sizing strategies and risk management techniques specifically designed for extended holding periods. Learn how to avoid the emotional decision-making that destroys most traders when markets move against them temporarily. This course covers dividend reinvestment, tax-efficient trading, and portfolio construction principles. You'll understand how to stay informed about long-term factors while ignoring short-term noise and market hysteria. Discover how successful long-term investors maintain their positions during crashes and corrections. Perfect for traders who prefer a more relaxed approach with significantly higher profit potential per trade, building wealth steadily over years.", "reviews": [] },
  { "_id": "9", "title": "Platform Basics: Introduction to MetaTrader", "price": "100", "discount": "0", "category": "Forex", "image": "/svg/laptop.svg", "details": "Master MetaTrader 4 and 5, the industry's most popular trading platforms. Learn all features and tools for professional trading.", "description": "Become exceptionally proficient with MetaTrader, unquestionably the platform of choice for millions of professional traders and institutions worldwide. This detailed and comprehensive course covers both MetaTrader 4 and MetaTrader 5 in exhaustive detail, guiding you systematically through every single feature and function available. You'll master navigation, understanding the terminal, market watch, and chart windows. Learn to create custom indicators using the MetaQuotes Language, giving you the power to implement your exact trading ideas. Explore how to automate your trading completely using Expert Advisors, allowing your trading system to run 24/7 without your constant attention. Understand order management including pending orders, position modification, and risk management settings. Learn to analyze charts with professional-grade tools including trend lines, channels, and custom indicators. This course covers backtesting your strategies to optimize performance before risking real capital. You'll understand account management, leverage settings, and spreads. Master the MQL4 and MQL5 programming languages to create sophisticated automated trading systems. By the end of this course, you'll navigate MetaTrader exactly like a seasoned professional trader with years of experience.", "reviews": [] },
  { "_id": "10", "title": "Platform Basics: Introduction to cTrader", "price": "110", "discount": "0", "category": "Forex", "image": "/svg/laptop.svg", "details": "Learn cTrader, the modern multi-asset trading platform. Discover advanced features and seamless execution tools.", "description": "Explore cTrader comprehensively, a cutting-edge and innovative platform designed specifically for serious traders seeking the most sophisticated analysis and execution tools available. This detailed course takes you thoroughly through cTrader's remarkably innovative and intuitive interface, advanced charting capabilities that rival any platform, and its powerful order management systems. You'll learn to leverage advanced algorithmic trading features that allow you to implement complex trading strategies. Understand how to customize your workspace completely according to your personal preferences and trading style. Utilize the platform's famously superior execution speed which can provide a significant competitive advantage in fast-moving markets. Learn to use the advanced order types including iceberg orders and trailing stops that aren't available on many competing platforms. Discover cTrader's unique features including the VolumeProfile indicator and sophisticated charting tools. This course covers cTrader Mobile for trading on the go, API connections for advanced users, and integration with third-party tools. Master portfolio management features and how to track multiple instruments simultaneously. You'll understand how cTrader's modern architecture and advanced features can give you a distinct edge in competitive markets. By the end, you'll master every aspect of this modern trading environment.", "reviews": [] },
  { "_id": "11", "title": "Platform Basics: Introduction to TradingView", "price": "120", "discount": "0", "category": "Forex", "image": "/svg/laptop.svg", "details": "Master TradingView, the premier charting and analysis platform. Learn advanced features for technical analysis and market insights.", "description": "Discover comprehensively why TradingView has become the undisputed go-to platform for technical analysis among millions of traders worldwide at all experience levels. This exceptionally comprehensive course teaches you to harness TradingView's incredibly powerful charting tools, advanced indicators, and innovative collaborative features that make it unique. Learn to create custom indicators using the Pine Script programming language, giving you unlimited possibilities for analysis. Analyze multiple timeframes simultaneously to make better-informed trading decisions based on complete market context. Identify trading opportunities across global markets in stocks, forex, cryptocurrencies, commodities, and more, all on a single unified platform. Understand how to use the platform's sophisticated alerts effectively to get notified of specific market conditions 24/7. Master watchlist creation and management to track hundreds of instruments efficiently. Learn how the TradingView community features allow you to share ideas and learn from thousands of other traders. This course covers advanced charting techniques, volume analysis, and market profile indicators. You'll understand how institutional traders use TradingView and how to implement their strategies. By the end, you'll master the platform that millions of traders rely on every single day for their market analysis.", "reviews": [] },
  { "_id": "12", "title": "TradingView Essentials for Beginners", "price": "130", "discount": "0", "category": "Forex", "image": "/svg/laptop.svg", "details": "Get started with TradingView's core features and tools. Perfect introduction to technical analysis using the world's premier charting platform.", "description": "Begin your comprehensive TradingView journey with this beginner-friendly course covering all of the platform's most essential and foundational features. You'll learn to read charts effectively, understanding candlestick patterns and what they reveal about market sentiment. Apply basic indicators including moving averages, RSI, and MACD with confidence. Conduct fundamental technical analysis using support and resistance levels, trend lines, and basic channel analysis. Understand how these basic tools work together to form a coherent trading system. Learn about different timeframe selection and what each timeframe reveals about market structure. Discover how to set up price alerts to be notified automatically when prices reach your target levels. Master watchlist creation and management to track your favorite instruments across multiple markets. Learn about the different order types and how to place trades directly from TradingView. Understand the basics of volume analysis and what it reveals about market strength. This course provides the absolutely perfect foundation for anyone looking to upgrade their technical analysis capabilities from basic charts to professional-grade tools. You'll build confidence and competence quickly through practical examples and exercises.", "reviews": [] },
  { "_id": "13", "title": "TradingView Mastery: Expert Level", "price": "140", "discount": "0", "category": "Forex", "image": "/svg/laptop.svg", "details": "Unlock advanced TradingView capabilities including Pine Script programming and expert strategies.", "description": "Take your TradingView expertise to the absolute highest possible level with this advanced course covering sophisticated strategies and deep technical implementation. Learn to code custom indicators and strategies using Pine Script, TradingView's powerful and flexible programming language. Master advanced charting techniques including market profile, volume profile, and sophisticated order flow analysis. Understand multi-timeframe analysis and how to use it to identify high-probability setups with confluences. Learn how to optimize your trading strategies using backtesting features to verify performance before risking real capital. Create automated alerts based on complex conditions combining multiple indicators and price action patterns. Discover how to publish your custom indicators and strategies on TradingView's marketplace. Master advanced features like drawing tools, pattern recognition, and custom indicators. Learn how professional traders use TradingView to manage their portfolios and spot market-wide patterns. Understand how to integrate Pine Script with your trading systems for maximum automation. This course transforms you into a TradingView expert capable of implementing even the most sophisticated trading solutions and gaining significant competitive advantages.", "reviews": [] },
  { "_id": "14", "title": "TradingView Mastery: Advanced Level", "price": "150", "discount": "0", "category": "Forex", "image": "/svg/laptop.svg", "details": "Advance your TradingView skills with professional-level strategies and indicator development.", "description": "Bridge the comprehensive gap between basic and expert-level TradingView usage with this detailed advanced course designed for serious traders. Learn intermediate Pine Script programming techniques to create custom indicators that match your specific trading methodology perfectly. Explore advanced analysis techniques including sophisticated market profile analysis, order flow analysis, and volume-based strategies. Understand how professional traders use TradingView to identify high-probability trading setups with multiple confirmations. Master the art of multi-timeframe analysis where you use multiple timeframes to identify patterns and confirm trades. Learn how to develop sophisticated trading systems that combine multiple indicators and price action patterns. Understand the psychology of technical analysis and how to avoid common analytical mistakes. Develop your personal indicator suite tailored to your exact trading style and preferences. This course covers advanced position management, profit taking strategies, and stop loss optimization. Master the integration of Pine Script with your overall trading approach. You'll develop sophisticated trading systems that provide a distinct competitive advantage in the markets. This course prepares you for the final step toward complete mastery of TradingView.", "reviews": [] },
  { "_id": "15", "title": "Online Trading Safety: How to Spot Scams", "price": "160", "discount": "0", "category": "Forex", "image": "/svg/login.svg", "details": "Protect yourself from trading scams and fraudulent schemes. Learn red flags and safety protocols for secure trading.", "description": "Safeguard your hard-earned capital and personal information with this absolutely essential course on trading security and fraud prevention. Learn to identify the most common and sophisticated scams specifically targeting traders, understanding exactly how fraudsters operate in the digital age. Recognize red flags before falling victim to fraudulent schemes including unrealistic promises of guaranteed returns, high-pressure sales tactics, and unlicensed brokers. Discover the best practices for choosing legitimate brokers by verifying licenses, checking regulatory status, and understanding their financial backing. Learn how to protect your trading accounts from unauthorized access through strong passwords, two-factor authentication, and secure communication. This course covers multiple types of scams including phishing schemes, Ponzi schemes, pump and dump schemes, and unauthorized account access. Understand what legitimate regulation looks like and how to verify broker credentials. Learn how to research brokers thoroughly before depositing any funds. Discover how to recover lost funds if you do become a victim of fraud. Master the psychology of scammers and how they manipulate people emotionally. By understanding these threats deeply, you'll trade with complete confidence knowing you've protected yourself and your investment from the growing threat of financial fraud.", "reviews": [] },
  { "_id": "16", "title": "Algorithmic Trading: Introduction to Bots (Part 1)", "price": "170", "discount": "0", "category": "Forex", "image": "/svg/bots.svg", "details": "Discover the world of automated trading with algorithmic bots. Learn fundamentals of bot-based trading strategies.", "description": "Enter the fascinating future of trading with algorithmic trading systems and sophisticated bots that execute trades with mechanical precision. Part 1 of this comprehensive series introduces the core concepts of automated trading, where algorithms execute trades based on predetermined criteria and conditions. Learn how bots eliminate emotional decision-making, one of the biggest obstacles to trading success. Understand how bots execute trades at inhuman speeds and frequencies, capturing opportunities that human traders simply cannot. Discover how bots operate 24/7 without fatigue, controlling your positions across all global markets even while you sleep. Understand the basic architecture of trading bots and how they process data, generate signals, and execute orders. Learn how bots can systematically execute complex strategies that would be impossible to manage manually. Explore different types of algorithms including trend-following bots, mean-reversion bots, and momentum bots. This course covers the fundamental concepts that power modern algorithmic trading. Understand how institutional traders use algorithms at massive scale. This course provides the foundation for understanding how modern algorithmic trading revolutionizes the markets and creates new opportunities.", "reviews": [] },
  { "_id": "17", "title": "Algorithmic Trading: Introduction to Bots (Part 2)", "price": "180", "discount": "0", "category": "Forex", "image": "/svg/bots.svg", "details": "Advance your algorithmic trading knowledge with strategy design and implementation techniques.", "description": "Deepen your comprehensive understanding of algorithmic trading with Part 2, focusing extensively on practical strategy design and real-world implementation. Learn in detail how to develop the precise trading logic that bots can execute reliably across different market conditions. Understand backtesting methodologies in depth, learning to test your strategies on historical data before risking real capital. Master the art of optimizing bot parameters for different market conditions, volatility levels, and timeframes. Discover exactly how to integrate multiple indicators and price patterns into bot logic for increased accuracy. Learn how to manage risk programmatically, implementing stop losses, position sizing, and portfolio-level risk controls. Understand the unique challenges of algorithmic trading including slippage, latency, and market impact. Learn how to handle edge cases and unexpected market conditions in your algorithms. Master the concept of walk-forward analysis to ensure your strategies work on out-of-sample data. Learn about overfitting and how to avoid developing strategies that work in the past but fail in live trading. This course prepares you to design and implement truly sophisticated automated trading systems that can trade profitably across market cycles.", "reviews": [] },
  { "_id": "18", "title": "Bot Development: Creating Custom Bots (Part 1)", "price": "190", "discount": "0", "category": "Forex", "image": "/svg/bots.svg", "details": "Learn to code trading bots from scratch. Build your first automated trading system with step-by-step guidance.", "description": "Transition from theoretical concepts to practical reality by building your own fully functional trading bots from complete scratch. Part 1 covers all the fundamentals of bot development, teaching you the comprehensive programming basics needed to create functional trading systems. Learn to connect to broker APIs, understanding exactly how to retrieve real-time market data. Master order execution, understanding how to place, modify, and cancel orders programmatically. Learn to structure your code professionally for reliability and maintainability. Understand the basic structure of a professional trading bot and the best practices for reliable automation. This hands-on course includes step-by-step code walkthroughs and practical projects you'll build yourself. Learn about different programming languages suitable for bot development including Python, C#, and JavaScript. Understand how to handle errors and unexpected conditions in your code. Master data handling and how to store and analyze trading data. Learn about logging and how to track your bot's activities. This practical course equips you with the core skills to develop bots tailored to your specific trading strategies and unique requirements.", "reviews": [] },
  { "_id": "19", "title": "Bot Development: Creating Custom Bots (Part 2)", "price": "200", "discount": "0", "category": "Forex", "image": "/svg/bots.svg", "details": "Master advanced bot development with complex strategies and risk management systems.", "description": "Complete your comprehensive bot development education with Part 2, focusing extensively on advanced implementations and sophisticated features. Learn to code complex multi-leg decision-making systems that handle intricate trading logic. Implement portfolio-level risk management that controls overall exposure across multiple positions and instruments. Master the integration of multiple data sources including price feeds, fundamental data, and alternative data. Discover how to build bots that adapt dynamically to market conditions, adjusting parameters and strategies based on changing environments. Learn how to optimize your bot's performance continuously using real-time metrics. Understand comprehensive logging and monitoring techniques essential for production-level bots. Master debugging and troubleshooting when your bot behaves unexpectedly. Learn how to safely deploy bots to live trading environments. Understand how to track and analyze your bot's performance metrics. By course end, you'll be capable of developing enterprise-quality trading bots that execute your most advanced trading strategies with precision and reliability.", "reviews": [] },
  { "_id": "20", "title": "AI in Trading: Creating AI Bots (Part 1)", "price": "210", "discount": "0", "category": "Forex", "image": "/svg/bots.svg", "details": "Explore artificial intelligence in trading. Learn machine learning fundamentals for creating intelligent trading bots.", "description": "Venture boldly into the cutting edge of trading technology with AI-powered trading systems and intelligent bots. Part 1 comprehensively introduces machine learning concepts as applied to financial markets. Learn how algorithms can learn from historical data to predict future price movements with increasing accuracy. Understand supervised learning techniques where you provide examples of correct answers to train models. Explore unsupervised learning to discover hidden patterns in market data. Master feature engineering for trading, understanding how to create the most predictive variables from raw market data. Learn how to properly prepare and normalize market data for machine learning models. Master the fundamentals of neural networks and deep learning architectures. Understand different neural network types including recurrent networks and convolutional networks. Learn how these powerful tools can identify patterns that human traders would never recognize. This course opens doors to creating bots that continuously improve through learning from market patterns. Understand the unique challenges of applying AI to financial markets including market regime changes.", "reviews": [] },
  { "_id": "21", "title": "AI in Trading: Creating AI Bots (Part 2)", "price": "220", "discount": "0", "category": "Forex", "image": "/svg/bots.svg", "details": "Develop sophisticated AI trading systems with neural networks and predictive models.", "description": "Build state-of-the-art AI trading bots with Part 2, which focuses intensively on implementing advanced machine learning models for practical trading. Learn in detail how to train neural networks on massive amounts of historical market data. Master parameter optimization using techniques like grid search and random search. Learn how to properly validate your models using rigorous methodologies including cross-validation. Understand how to handle overfitting, the enemy of machine learning, where models memorize historical data but fail on new data. Master market regime changes and how to detect when market conditions shift. Learn how to deploy AI systems responsibly with proper risk controls. Understand the integration of AI predictions with your trading execution systems. Learn how to monitor your AI models in production and detect performance degradation. Master the unique challenges of machine learning in finance including non-stationary data and regime shifts. This advanced course prepares you to leverage artificial intelligence for maximum trading potential while fully understanding the unique challenges of machine learning in financial markets.", "reviews": [] },
  { "_id": "22", "title": "Cryptocurrency Basics: Introduction to Crypto (Part 1)", "price": "230", "discount": "0", "category": "Forex", "image": "/svg/cryptotrading.svg", "details": "Master cryptocurrency fundamentals. Learn blockchain technology and digital asset trading basics.", "description": "Begin your comprehensive cryptocurrency journey with a solid and unshakeable foundation in blockchain technology and digital assets. Part 1 thoroughly covers the revolutionary technology behind cryptocurrencies and how it works. Understand the complete history of Bitcoin and how it emerged as the first successful implementation of blockchain technology. Learn in detail how blockchain secures transactions through cryptographic hashing and consensus mechanisms. Explore different types of cryptocurrencies and what distinguishes them, including altcoins and tokens. Master wallet management and the different types of wallets from hot wallets to cold storage. Learn about exchanges and how to safely trade cryptocurrencies on reputable platforms. Understand the unique characteristics that make crypto markets distinct from traditional forex and equity markets. Discover the 24/7 nature of crypto markets and what that means for traders. Learn about regulatory considerations and compliance in the crypto space. Master the fundamentals of blockchain technology including consensus mechanisms, smart contracts, and decentralized applications. Perfect for traders new to the crypto space seeking a comprehensive introduction to this dynamic market segment with massive growth potential.", "reviews": [] },
  { "_id": "23", "title": "Cryptocurrency Basics: Introduction to Crypto (Part 2)", "price": "240", "discount": "0", "category": "Forex", "image": "/svg/cryptotrading.svg", "details": "Deepen your crypto knowledge with advanced concepts and market analysis techniques.", "description": "Continue your comprehensive cryptocurrency education with Part 2, exploring advanced concepts and specialized analysis techniques specific to crypto markets. Learn about smart contracts in detail and how they power decentralized finance applications. Master tokenomics and understand how the economic incentives of different cryptocurrencies influence their value. Learn how different cryptocurrencies solve specific problems and what unique value propositions they offer. Understand the factors driving crypto valuations, which differ significantly from traditional assets. Master regulatory considerations and how government policies impact crypto prices. Learn security best practices to protect your cryptocurrency holdings from theft and hacks. Discover technical analysis specific to cryptocurrency markets where patterns often differ from traditional markets. Learn how to identify emerging trends and upcoming technologies in the crypto space. Master on-chain analysis and what blockchain data reveals about market sentiment. Learn about DeFi protocols and how they create trading opportunities. This course provides the knowledge needed to trade cryptocurrencies confidently while thoroughly understanding the fundamental drivers of this rapidly evolving and dynamic asset class.", "reviews": [] },
  { "_id": "24", "title": "Bitcoin for Beginners: Getting Started", "price": "250", "discount": "0", "category": "Forex", "image": "/svg/cryptotrading.svg", "details": "Start your Bitcoin trading journey. Learn the essentials of the world's leading cryptocurrency.", "description": "Focus specifically and intently on Bitcoin, the cryptocurrency that started the entire digital asset revolution and remains the most important. This comprehensive beginner course teaches you absolutely everything needed to trade Bitcoin effectively and profitably. Understand Bitcoin's unique properties that distinguish it from all other cryptocurrencies and digital assets. Learn about Bitcoin halving cycles and how they influence the long-term price trajectory. Understand the factors that influence Bitcoin's price including macroeconomic factors, regulatory news, and technological developments. Learn how to securely store Bitcoin using different wallet types from user-friendly options to Fort Knox-level security. Master different trading platforms and how to choose the one that best matches your needs. Learn how to protect yourself from the unique scams and risks specific to Bitcoin. Discover the historical performance of Bitcoin and its role as a store of value. Master Bitcoin's correlation with other assets and how it can fit into a diversified portfolio. Learn about Lightning Network and other scaling solutions. This course is absolutely essential for any trader looking to participate in Bitcoin markets with confidence and competence.", "reviews": [] },
  { "_id": "25", "title": "Bitcoin Mastery: Expert Guide", "price": "260", "discount": "0", "category": "Forex", "image": "/svg/cryptotrading.svg", "details": "Become a Bitcoin expert with advanced strategies and sophisticated analysis techniques.", "description": "Achieve true mastery in Bitcoin trading with this expert-level course covering the most sophisticated strategies and deepest analysis available. Learn on-chain analysis techniques in detail, understanding how professional traders use blockchain data to spot Bitcoin accumulation and distribution patterns. Master advanced technical analysis specific to Bitcoin, including the unique patterns that emerge in crypto markets. Discover in detail how institutional investors trade Bitcoin and the impact of their large transactions on price movements. Understand the relationship between different timeframes and what multi-timeframe analysis reveals about Bitcoin's true direction. Master the art of anticipating major Bitcoin price moves using a combination of technical, fundamental, and sentiment analysis. Learn how to identify critical support and resistance levels that institutional traders watch. Understand how to read order books and recognize accumulation versus distribution patterns. Master volatility analysis and how to profit during both quiet periods and explosive moves. Learn about correlation analysis and how Bitcoin's relationship with other assets changes. This course transforms you into a Bitcoin expert capable of executing professional-grade trading strategies with sophistication and precision.", "reviews": [] },
  { "_id": "26", "title": "Bitcoin Mastery: Advanced Guide", "price": "270", "discount": "0", "category": "Forex", "image": "/svg/cryptotrading.svg", "details": "Perfect your Bitcoin trading with advanced techniques and strategic portfolio approaches.", "description": "Progress to the absolute highest levels of Bitcoin trading knowledge with this comprehensive advanced guide. Learn hedging strategies that protect your Bitcoin holdings from adverse price movements while maintaining upside participation. Master options trading on Bitcoin, understanding calls, puts, spreads, and other sophisticated strategies. Develop portfolio management techniques specifically tailored to crypto assets with their unique characteristics. Understand the correlation between Bitcoin and traditional assets like stocks, bonds, and commodities. Discover how to use derivatives markets effectively to amplify returns while managing leverage risk. Master the psychological aspects of Bitcoin trading and how to maintain unshakeable discipline during extreme market volatility. Learn how to manage your emotions during 50% drawdowns and stay focused on your strategy. Master position sizing and portfolio allocation strategies for crypto. Learn how to trade Bitcoin across multiple timeframes and market conditions. Understand how to adapt your strategies to different market regimes. This comprehensive course provides everything needed to trade Bitcoin at the absolute professional level with complete mastery and confidence.", "reviews": [] },
  { "_id": "27", "title": "Precious Metals: Introduction to Gold (Part 1)", "price": "250", "discount": "0", "category": "Forex", "image": "/svg/forextrading.svg", "details": "Discover gold trading fundamentals. Learn the factors driving gold prices and basic trading strategies.", "description": "Explore comprehensively the precious metals markets, starting with gold trading fundamentals and core concepts. Part 1 thoroughly introduces you to the gold market structure, the historical significance of gold, and the modern mechanisms for trading. Learn about gold supply and demand dynamics and how they influence prices long-term. Master geopolitical factors that affect gold prices, including central bank policies and currency fluctuations. Understand how to trade gold effectively across multiple market vehicles including spot gold, gold futures, and gold ETFs. Learn the role of gold as a safe-haven asset during times of economic uncertainty and financial crisis. Understand gold's relationship with currency values and how a weakening dollar supports gold prices. Discover different ways to gain exposure to gold including physical gold, paper gold, and allocated accounts. Master the basics of gold technical analysis and how to identify trends. Learn about gold's carry trade characteristics and interest rate sensitivity. This course prepares you to trade one of the world's most stable, universally recognized, and historically important assets with confidence.", "reviews": [] },
  { "_id": "28", "title": "Precious Metals: Introduction to Gold (Part 2)", "price": "260", "discount": "0", "category": "Forex", "image": "/svg/forextrading.svg", "details": "Advance your gold trading with technical analysis and macro-economic factors.", "description": "Deepen your gold trading expertise considerably with Part 2, focusing extensively on technical analysis and macroeconomic factors. Learn in detail how central bank policies directly influence gold prices and how to anticipate major market moves. Understand the relationship between gold and interest rates, where rising rates typically pressure gold prices. Master inflation expectations and how expectations of future inflation drive investment in gold. Learn how currency movements, particularly US dollar strength, fundamentally affect gold prices. Understand technical analysis specific to gold markets, including how to identify trend patterns and support/resistance levels. Master gold's seasonal patterns and how to position yourself for maximum profitability. Learn how to use gold in macroeconomic trading strategies that correlate with broader economic cycles. Understand gold's role in a diversified portfolio and how it provides downside protection. Master the leverage available in gold futures and how to manage risk appropriately. This course elevates your gold trading from basic to truly professional standards with comprehensive understanding.", "reviews": [] },
  { "_id": "29", "title": "Gold Trading: Candlesticks & Patterns (Part 1)", "price": "280", "discount": "0", "category": "Forex", "image": "/svg/priceaction.svg", "details": "Master candlestick analysis for gold trading. Learn to read and interpret price patterns.", "description": "Develop profound expertise in candlestick analysis as specifically applied to gold trading and markets. Part 1 thoroughly covers the fundamentals of candlestick interpretation, teaching you to identify single candlestick patterns and multiple candlestick formations with complete understanding. Learn exactly what each candlestick formation reveals about market sentiment, momentum, and potential future price action. Master how to interpret candlestick shadows, bodies, and overall shapes. Understand how different candlestick patterns form in bull markets versus bear markets. Learn the most reliable candlestick patterns for identifying reversals versus continuations. Understand how to use candlesticks to identify precise entry and exit points in gold trading. Discover how professional gold traders use candlestick patterns to make high-probability trades with proper risk-reward. Learn how to combine candlestick patterns with other technical indicators for increased accuracy. Master the concept of confluence where multiple patterns align to create high-probability trades. This course provides the absolute technical foundation needed for consistent and profitable gold trading success.", "reviews": [] },
  { "_id": "30", "title": "Gold Trading: Candlesticks & Patterns (Part 2)", "price": "290", "discount": "0", "category": "Forex", "image": "/svg/priceaction.svg", "details": "Advance your candlestick mastery with complex patterns and confluence strategies.", "description": "Build significantly upon candlestick fundamentals with Part 2, exploring complex patterns and sophisticated confluence analysis. Learn to identify complex multi-candlestick patterns that reliably signal major price reversals and continuations. Discover how to combine candlestick patterns with volume analysis for dramatically increased accuracy. Understand the psychology behind each pattern and exactly how market participants drive price movements. Learn how to use candlesticks in multi-timeframe analysis to identify setups with the highest probability. Master the concept of trading confluence where multiple technical signals align perfectly. Understand how to manage risk effectively when trading candlestick patterns and position sizing strategies. Learn how to identify the most profitable candlestick patterns for different market conditions. Master how to trade candlestick patterns across different timeframes. Understand how candlestick analysis works specifically in gold markets with their unique characteristics. This advanced course transforms you into a master of candlestick analysis for gold trading with professional-level skill.", "reviews": [] },
  { "_id": "31", "title": "Gold Trading: Candlesticks & Patterns (Part 3)", "price": "300", "discount": "0", "category": "Forex", "image": "/svg/priceaction.svg", "details": "Complete your candlestick mastery with professional-level pattern strategies and risk management.", "description": "Conclude your comprehensive candlestick education with Part 3, focusing exclusively on professional implementation and risk management. Learn exactly how institutional traders use candlestick analysis within comprehensive and sophisticated trading systems. Master the integration of candlestick patterns with volume analysis, support and resistance, and momentum indicators. Discover the precise techniques for managing risk effectively when trading candlestick-based patterns. Learn professional position sizing that matches your account size and risk tolerance. Understand how to adapt candlestick strategies to different market conditions and market regimes. Master how to trade candlestick patterns across different timeframes for maximum flexibility. Learn how to combine candlestick patterns with other technical analysis methods for superior results. Understand how professional traders use candlesticks as part of larger trading systems. Master the psychology of pattern trading and how to maintain discipline. This final comprehensive module prepares you for expert-level gold trading based on candlestick analysis with true professional mastery.", "reviews": [] },
  { "_id": "32", "title": "Precious Metals: Introduction to Silver (Part 1)", "price": "310", "discount": "0", "category": "Forex", "image": "/svg/forextrading.svg", "details": "Enter the silver market with fundamental knowledge and trading strategies.", "description": "Explore silver trading comprehensively, one of the most dynamic and volatile precious metals markets available. Part 1 provides foundational knowledge about silver's industrial applications and how they drive demand. Learn about silver's dual nature as both an industrial metal and a precious metal. Understand silver supply and demand dynamics and how they influence prices. Discover the different silver products available for trading from physical silver to silver futures and ETFs. Learn how silver correlates with other assets including gold, base metals, and equities. Understand the unique characteristics of silver trading compared to gold, including higher volatility and greater leverage. Learn about silver's historical price patterns and how to identify trends. Discover how to identify silver trading opportunities using fundamental analysis. Master the basics of silver technical analysis and chart patterns. This course is absolutely perfect for traders seeking exposure to a precious metal with unique and profitable market characteristics.", "reviews": [] },
  { "_id": "33", "title": "Precious Metals: Introduction to Silver (Part 2)", "price": "320", "discount": "0", "category": "Forex", "image": "/svg/forextrading.svg", "details": "Advance your silver trading with technical analysis and volatility strategies.", "description": "Deepen your silver trading knowledge considerably with Part 2, focusing extensively on technical analysis and capitalizing on silver's higher volatility. Learn exactly how to use silver's price swings to your advantage through multiple trading strategies. Understand the factors that create silver price spikes and how to position yourself appropriately to profit. Master technical analysis specifically applied to silver markets with all their unique characteristics. Learn how to identify silver breakouts and reversals with precision. Discover how the silver to gold ratio provides valuable trading insights and relative value information. Master how to trade silver using moving averages, oscillators, and other technical indicators. Learn how to use leverage appropriately to amplify silver trading returns. Understand risk management for volatile silver positions. Learn how to read silver market sentiment and commercial positioning. This course prepares you to trade silver confidently, profitably, and with proper risk control throughout all market conditions.", "reviews": [] },
  { "_id": "34", "title": "Precious Metals: Introduction to Silver (Part 3)", "price": "330", "discount": "0", "category": "Forex", "image": "/svg/forextrading.svg", "details": "Master advanced silver trading strategies and portfolio integration.", "description": "Complete your comprehensive silver trading education with Part 3, covering advanced strategies and sophisticated portfolio management. Learn exactly how professional traders use silver to hedge against currency fluctuations and inflation risk. Discover advanced technical analysis for silver markets and how to identify the highest probability trades. Master how to integrate silver trading into a diversified portfolio and manage correlation risks effectively. Learn to trade silver futures, options, and ETFs with sophistication and precision. Master spreads and arbitrage opportunities in silver markets. Understand how to manage leverage and margin requirements effectively. Learn portfolio-level risk management when incorporating silver. Understand how to use silver in macroeconomic trading strategies. Master the emotional and psychological aspects of trading volatile assets like silver. This comprehensive course positions you as a sophisticated silver trader capable of executing the most complex trading strategies with complete mastery.", "reviews": [] },
  { "_id": "35", "title": "Silver Trading: Candlesticks & Patterns (Part 1)", "price": "340", "discount": "0", "category": "Forex", "image": "/svg/priceaction.svg", "details": "Master candlestick patterns in silver trading. Learn precise entry and exit techniques.", "description": "Apply candlestick analysis specifically to silver markets with this comprehensive and detailed course. Part 1 thoroughly covers candlestick fundamentals while highlighting silver-specific price patterns and behaviors. Learn to identify single and multi-candlestick formations that signal reliable and profitable trading opportunities in silver. Understand exactly how silver's volatility affects candlestick patterns compared to gold and other assets. Discover how to use candlestick analysis to time entries and exits with precision and confidence. Master how to read candlestick wicks and what they reveal about buying and selling pressure. Learn the most profitable candlestick patterns specific to silver markets. Understand how to combine candlesticks with silver fundamentals for superior analysis. Master how to use candlesticks on different timeframes from minutes to weeks. This course provides the essential technical tools needed to trade silver confidently using proven candlestick methods.", "reviews": [] },
  { "_id": "36", "title": "Silver Trading: Candlesticks & Patterns (Part 2)", "price": "350", "discount": "0", "category": "Forex", "image": "/svg/priceaction.svg", "details": "Advance your silver candlestick trading with complex patterns and system integration.", "description": "Build advanced candlestick expertise specifically tailored to silver trading with Part 2. Learn to recognize complex multi-candlestick patterns that reliably precede major silver price moves. Understand exactly how to combine candlestick analysis with volume and momentum indicators for dramatically increased accuracy. Discover professional trading systems built specifically around candlestick patterns for silver. Master multi-timeframe candlestick analysis to identify setups with the highest probability of success. Understand how to adapt candlestick strategies to silver's unique volatility characteristics. Learn how to manage risk when trading volatile silver positions. Master how to use candlesticks to catch major silver rallies and collapses. Learn how to trade candlestick patterns during different market regimes. This course transforms you into a sophisticated and skilled candlestick trader in silver markets.", "reviews": [] },
  { "_id": "37", "title": "Silver Trading: Candlesticks & Patterns (Part 3)", "price": "360", "discount": "0", "category": "Forex", "image": "/svg/priceaction.svg", "details": "Achieve mastery in silver candlestick trading with professional strategies and execution.", "description": "Achieve complete and utter mastery of candlestick trading in silver markets with Part 3. Learn precisely how institutional traders use candlestick patterns within comprehensive and sophisticated professional trading frameworks. Master the complete integration of candlestick patterns with risk management, position sizing, and portfolio strategies. Discover exactly how to trade candlestick patterns across different timeframes and multiple market conditions. Understand the psychological aspects of pattern trading and how to maintain unshakeable discipline in silver's volatile environment. Master professional execution techniques and advanced money management specifically for silver trading. Learn how to identify the most profitable candlestick patterns for your personal trading style. Master how to adapt candlestick patterns as market conditions and volatility levels change. Learn how to optimize your candlestick-based system for maximum profitability. Understand how to combine candlesticks with other trading methods for superior results. This final comprehensive module prepares you for expert-level silver trading using candlestick methodology at the absolute highest professional level.", "reviews": [] }
];

// Create axios instance with default config
const axiosInstance = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    "Content-Type": "application/json",
    Accept: "application/json",
  },
  withCredentials: true,
});

class CoursesAPI {
  static async getAllCourses(params = {}) {
    // Use mock data as primary source
    console.log("Loading courses from mock data with params:", params);
    return this.getCoursesFromMockData(params);
  }

  static async getCoursesFromMockData(params = {}) {
    try {
      const mockCourses = forexCoursesData;

      // Apply filters
      let filtered = mockCourses;

      // Category filter
      if (params.category) {
        filtered = filtered.filter(course =>
          course.category?.toLowerCase() === params.category?.toLowerCase()
        );
      }

      // Price range filter
      if (params.priceFrom !== undefined) {
        filtered = filtered.filter(course =>
          parseFloat(course.price) >= params.priceFrom
        );
      }
      if (params.priceTo !== undefined) {
        filtered = filtered.filter(course =>
          parseFloat(course.price) <= params.priceTo
        );
      }

      // Search filter
      if (params.search) {
        const searchLower = params.search.toLowerCase();
        filtered = filtered.filter(course =>
          course.title?.toLowerCase().includes(searchLower) ||
          course.details?.toLowerCase().includes(searchLower)
        );
      }

      // Pagination
      const page = params.page || 1;
      const limit = params.limit || 12;
      const skip = (page - 1) * limit;
      const paginatedCourses = filtered.slice(skip, skip + limit);

      return {
        data: {
          data: paginatedCourses,
          total: filtered.length,
          page: page,
          pages: Math.ceil(filtered.length / limit)
        }
      };
    } catch (error) {
      console.error("Error loading mock courses:", error);
      return { data: { data: [] } };
    }
  }

  static async getCourseById(id) {
    // Use mock data as primary source
    console.log("Looking for course with ID:", id, "Type:", typeof id);
    console.log("Available mock courses:", forexCoursesData.map(c => ({ _id: c._id, title: c.title })));

    const mockCourse = forexCoursesData.find(course => {
      return String(course._id) === String(id);
    });

    if (mockCourse) {
      console.log("Found mock course:", mockCourse.title);
      return { data: { data: mockCourse } };
    }

    console.log("Course not found in mock data, attempting API");

    // Fallback to API if course not found in mock data
    try {
      const response = await axiosInstance.get(`/courses/${id}`);
      return response.data;
    } catch (error) {
      console.error("Error fetching course from API:", error);
      throw new Error("Course not found");
    }
  }

  /**
   * Get unique categories from courses
   * @returns {Promise} Array of categories
   */
  static async getCategories() {
    try {
      const response = await axiosInstance.get("/courses");
      const courses = response.data.data.data;
      const categories = [...new Set(courses.map((course) => course.category))];
      return categories.filter(Boolean); // Remove empty values
    } catch (error) {
      console.error("Error fetching categories from API, using mock data:", error);
      // Fallback to mock data
      const mockCourses = forexCoursesData;
      const categories = [...new Set(mockCourses.map((course) => course.category))];
      return categories.filter(Boolean);
    }
  }

  /**
   * Get price range from all courses
   * @returns {Promise} Object with min and max prices
   */
  static async getPriceRange() {
    try {
      const response = await axiosInstance.get("/courses");
      const courses = response.data.data.data;

      if (courses.length === 0) {
        return { min: 0, max: 1000 };
      }

      const prices = courses
        .map((course) => parseFloat(course.price))
        .filter((price) => !isNaN(price));

      return {
        min: Math.min(...prices),
        max: Math.max(...prices),
      };
    } catch (error) {
      console.error("Error fetching price range from API, using mock data:", error);
      // Fallback to mock data
      try {
        const mockCourses = forexCoursesData;

        if (mockCourses.length === 0) {
          return { min: 0, max: 1000 };
        }

        const prices = mockCourses
          .map((course) => parseFloat(course.price))
          .filter((price) => !isNaN(price));

        return {
          min: Math.min(...prices),
          max: Math.max(...prices),
        };
      } catch (mockError) {
        console.error("Error loading mock price range:", mockError);
        return { min: 0, max: 1000 };
      }
    }
  }

  static filterCoursesByPrice(courses, priceFrom, priceTo) {
    return courses.filter((course) => {
      const price = parseFloat(course.price);
      if (isNaN(price)) return false;

      const minPrice = priceFrom !== undefined ? priceFrom : 0;
      const maxPrice = priceTo !== undefined ? priceTo : Infinity;

      return price >= minPrice && price <= maxPrice;
    });
  }

  static buildUrlWithParams(baseUrl, params) {
    const url = new URL(baseUrl, window.location.origin);

    Object.entries(params).forEach(([key, value]) => {
      if (value !== undefined && value !== null && value !== "") {
        url.searchParams.set(key, value);
      }
    });

    return url.pathname + url.search;
  }
}

export default CoursesAPI;
