const forexCoursesData = [
  {
    "_id": "1",
    "title": "Beginner's Guide to Trading: Types of Trading (Part 1)",
    "price": "20",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master the fundamentals of trading by exploring different trading styles.",
    "description": "Welcome to your journey into the world of trading. Part 1 of our beginner's guide explores the foundation of successful trading by breaking down the various types of trading approaches available to modern traders.",
    "reviews": []
  },
  {
    "_id": "2",
    "title": "Beginner's Guide to Trading: Types of Trading (Part 2)",
    "price": "30",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Continue your trading education with advanced trading types and hybrid strategies.",
    "description": "Build upon your foundational knowledge with Part 2 of our beginner's guide. This course delves deeper into specialized trading types and hybrid strategies that blend multiple approaches.",
    "reviews": []
  },
  {
    "_id": "3",
    "title": "Beginner's Guide to Trading: Types of Trading (Part 3)",
    "price": "40",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Complete your foundational understanding with advanced concepts and practical applications.",
    "description": "Conclude your beginner's trading journey with Part 3, where theory meets practice. This final module of the Types of Trading series focuses on practical application and real-world execution.",
    "reviews": []
  },
  {
    "_id": "4",
    "title": "Getting Started: Introduction to Trading Platforms",
    "price": "50",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Get hands-on experience with industry-standard trading platforms.",
    "description": "Explore the digital tools that power modern trading. This comprehensive course introduces you to leading trading platforms used by professionals worldwide.",
    "reviews": []
  },
  {
    "_id": "5",
    "title": "Trading Strategies: Introduction to Scalp Trading",
    "price": "60",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master the art of quick profits with scalp trading.",
    "description": "Discover one of the most dynamic trading strategies in the financial markets. This course introduces you to scalp trading, a technique focused on capturing small price movements over short timeframes.",
    "reviews": []
  },
  {
    "_id": "6",
    "title": "Trading Strategies: Introduction to Swing Trading",
    "price": "70",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Capitalize on medium-term price swings with swing trading.",
    "description": "Transform your understanding of intermediate-term trading with our swing trading course. This strategy focuses on capturing price swings that typically last from days to weeks.",
    "reviews": []
  },
  {
    "_id": "7",
    "title": "Trading Strategies: Introduction to Intraday Trading",
    "price": "80",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master day-to-day trading strategies that capitalize on daily price movements.",
    "description": "Enter the exciting world of intraday trading where fortunes can be made within a single trading session. This comprehensive course teaches you the strategies, timing, and psychology of day traders.",
    "reviews": []
  },
  {
    "_id": "8",
    "title": "Trading Strategies: Introduction to Long-Term Trading",
    "price": "90",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Build wealth through patient, strategic long-term investing.",
    "description": "Discover the power of patience and strategic positioning in long-term trading. This course explores strategies for traders who believe in holding positions through multiple market cycles.",
    "reviews": []
  },
  {
    "_id": "9",
    "title": "Platform Basics: Introduction to MetaTrader",
    "price": "100",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master MetaTrader 4 and 5, the industry's most popular trading platforms.",
    "description": "Become proficient with MetaTrader, the platform of choice for millions of traders worldwide. This detailed course covers both MetaTrader 4 and 5.",
    "reviews": []
  },
  {
    "_id": "10",
    "title": "Platform Basics: Introduction to cTrader",
    "price": "110",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Learn cTrader, the modern multi-asset trading platform.",
    "description": "Explore cTrader, a cutting-edge platform designed for serious traders seeking sophisticated analysis and execution tools.",
    "reviews": []
  },
  {
    "_id": "11",
    "title": "Platform Basics: Introduction to TradingView",
    "price": "120",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master TradingView, the premier charting and analysis platform.",
    "description": "Discover why TradingView has become the go-to platform for technical analysis worldwide. This comprehensive course teaches you to harness TradingView's powerful charting tools.",
    "reviews": []
  },
  {
    "_id": "12",
    "title": "TradingView Essentials for Beginners",
    "price": "130",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Get started with TradingView's core features and tools.",
    "description": "Begin your TradingView journey with this beginner-friendly course covering the platform's most essential features.",
    "reviews": []
  },
  {
    "_id": "13",
    "title": "TradingView Mastery: Expert Level",
    "price": "140",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Unlock advanced TradingView capabilities including Pine Script programming and expert strategies.",
    "description": "Take your TradingView expertise to the highest level with this advanced course.",
    "reviews": []
  },
  {
    "_id": "14",
    "title": "TradingView Mastery: Advanced Level",
    "price": "150",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Advance your TradingView skills with professional-level strategies and indicator development.",
    "description": "Bridge the gap between basic and expert-level TradingView usage with this advanced course.",
    "reviews": []
  },
  {
    "_id": "15",
    "title": "Online Trading Safety: How to Spot Scams",
    "price": "160",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Protect yourself from trading scams and fraudulent schemes.",
    "description": "Safeguard your capital and personal information with this essential course on trading security.",
    "reviews": []
  },
  {
    "_id": "16",
    "title": "Algorithmic Trading: Introduction to Bots (Part 1)",
    "price": "170",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Discover the world of automated trading with algorithmic bots.",
    "description": "Enter the future of trading with algorithmic trading systems and bots.",
    "reviews": []
  },
  {
    "_id": "17",
    "title": "Algorithmic Trading: Introduction to Bots (Part 2)",
    "price": "180",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Advance your algorithmic trading knowledge with strategy design and implementation techniques.",
    "description": "Deepen your understanding of algorithmic trading with Part 2.",
    "reviews": []
  },
  {
    "_id": "18",
    "title": "Bot Development: Creating Custom Bots (Part 1)",
    "price": "190",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Learn to code trading bots from scratch.",
    "description": "Transition from theory to practice by building your own trading bots.",
    "reviews": []
  },
  {
    "_id": "19",
    "title": "Bot Development: Creating Custom Bots (Part 2)",
    "price": "200",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master advanced bot development with complex strategies and risk management systems.",
    "description": "Complete your bot development education with Part 2.",
    "reviews": []
  },
  {
    "_id": "20",
    "title": "AI in Trading: Creating AI Bots (Part 1)",
    "price": "210",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Explore artificial intelligence in trading.",
    "description": "Venture into the cutting edge of trading technology with AI-powered trading systems.",
    "reviews": []
  },
  {
    "_id": "21",
    "title": "AI in Trading: Creating AI Bots (Part 2)",
    "price": "220",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Develop sophisticated AI trading systems with neural networks and predictive models.",
    "description": "Build state-of-the-art AI trading bots with Part 2.",
    "reviews": []
  },
  {
    "_id": "22",
    "title": "Cryptocurrency Basics: Introduction to Crypto (Part 1)",
    "price": "230",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master cryptocurrency fundamentals.",
    "description": "Begin your cryptocurrency journey with a solid foundation in blockchain technology.",
    "reviews": []
  },
  {
    "_id": "23",
    "title": "Cryptocurrency Basics: Introduction to Crypto (Part 2)",
    "price": "240",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Deepen your crypto knowledge with advanced concepts and market analysis techniques.",
    "description": "Continue your cryptocurrency education with Part 2.",
    "reviews": []
  },
  {
    "_id": "24",
    "title": "Bitcoin for Beginners: Getting Started",
    "price": "250",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Start your Bitcoin trading journey.",
    "description": "Focus specifically on Bitcoin, the cryptocurrency that started it all.",
    "reviews": []
  },
  {
    "_id": "25",
    "title": "Bitcoin Mastery: Expert Guide",
    "price": "260",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Become a Bitcoin expert with advanced strategies and sophisticated analysis techniques.",
    "description": "Achieve mastery in Bitcoin trading with this expert-level course.",
    "reviews": []
  },
  {
    "_id": "26",
    "title": "Bitcoin Mastery: Advanced Guide",
    "price": "270",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Perfect your Bitcoin trading with advanced techniques and strategic portfolio approaches.",
    "description": "Progress to the highest levels of Bitcoin trading knowledge.",
    "reviews": []
  },
  {
    "_id": "27",
    "title": "Precious Metals: Introduction to Gold (Part 1)",
    "price": "250",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Discover gold trading fundamentals.",
    "description": "Explore the precious metals markets, starting with gold trading fundamentals.",
    "reviews": []
  },
  {
    "_id": "28",
    "title": "Precious Metals: Introduction to Gold (Part 2)",
    "price": "260",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Advance your gold trading with technical analysis and macro-economic factors.",
    "description": "Deepen your gold trading expertise with Part 2.",
    "reviews": []
  },
  {
    "_id": "29",
    "title": "Gold Trading: Candlesticks & Patterns (Part 1)",
    "price": "280",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master candlestick analysis for gold trading.",
    "description": "Develop expertise in candlestick analysis applied specifically to gold trading.",
    "reviews": []
  },
  {
    "_id": "30",
    "title": "Gold Trading: Candlesticks & Patterns (Part 2)",
    "price": "290",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Advance your candlestick mastery with complex patterns and confluence strategies.",
    "description": "Build on candlestick fundamentals with Part 2.",
    "reviews": []
  },
  {
    "_id": "31",
    "title": "Gold Trading: Candlesticks & Patterns (Part 3)",
    "price": "300",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Complete your candlestick mastery with professional-level pattern strategies and risk management.",
    "description": "Conclude your candlestick education with Part 3.",
    "reviews": []
  },
  {
    "_id": "32",
    "title": "Precious Metals: Introduction to Silver (Part 1)",
    "price": "310",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Enter the silver market with fundamental knowledge and trading strategies.",
    "description": "Explore silver trading, one of the most dynamic precious metals markets.",
    "reviews": []
  },
  {
    "_id": "33",
    "title": "Precious Metals: Introduction to Silver (Part 2)",
    "price": "320",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Advance your silver trading with technical analysis and volatility strategies.",
    "description": "Deepen your silver trading knowledge with Part 2.",
    "reviews": []
  },
  {
    "_id": "34",
    "title": "Precious Metals: Introduction to Silver (Part 3)",
    "price": "330",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master advanced silver trading strategies and portfolio integration.",
    "description": "Complete your silver trading education with Part 3.",
    "reviews": []
  },
  {
    "_id": "35",
    "title": "Silver Trading: Candlesticks & Patterns (Part 1)",
    "price": "340",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Master candlestick patterns in silver trading.",
    "description": "Apply candlestick analysis specifically to silver markets.",
    "reviews": []
  },
  {
    "_id": "36",
    "title": "Silver Trading: Candlesticks & Patterns (Part 2)",
    "price": "350",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Advance your silver candlestick trading with complex patterns and system integration.",
    "description": "Build advanced candlestick expertise specific to silver trading.",
    "reviews": []
  },
  {
    "_id": "37",
    "title": "Silver Trading: Candlesticks & Patterns (Part 3)",
    "price": "360",
    "discount": "0",
    "category": "Forex",
    "image": "/forexcourse.png",
    "details": "Achieve mastery in silver candlestick trading with professional strategies and execution.",
    "description": "Achieve complete mastery of candlestick trading in silver markets.",
    "reviews": []
  }
];

module.exports = forexCoursesData;
